name: Node.js Package Lint, Test and Publish

on:
  push:
    branches:
      - "master"

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    services:
      intercom:
        image: kikstart/graphql-intercom
        ports:
          - 4567/tcp
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn
      - run: yarn lint
      - run: yarn test
        env:
          GRAPHQL_CLIENT_URI: http://localhost:${{ job.services.intercom.port[4567] }}
          GRAPHQL_CLIENT_WSURI: ws://localhost:${{ job.services.intercom.port[4567] }}

  # Publishing to gpr automatically published to npm too
  build-and-publish-gpr:
    needs: lint-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
      - run: yarn
      - run: yarn build
      - run: yarn semantic-release
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
          GH_TOKEN: ${{secrets.GH_TOKEN}}
          CI: true
  #  Uncomment this for a direct publish to npm
  build-and-publish-npm:
    needs: build-and-publish-gpr
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: yarn
      - run: yarn build
      - run: yarn semantic-release
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          GH_TOKEN: ${{secrets.GH_TOKEN}}
