name: Node.js Package Lint And Test

on:
  push:
    branches:
      - "*"
      - "!master"
  pull_request:
    branches:
      - "*"

jobs:
  lint-and-test:
    name: Test on node ${{ matrix.node-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [10, 12]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    services:
      intercom:
        image: kikstart/graphql-intercom
        ports:
          - 4567/tcp

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - run: npm run lint
      - run: npm run build
      - run: npm test
        env:
          GRAPHQL_CLIENT_URI: http://localhost:${{ job.services.intercom.port[4567] }}
          GRAPHQL_CLIENT_WSURI: ws://localhost:${{ job.services.intercom.port[4567] }}
